language: php

php:
  - 7.4
  - 8.0
  - 8.2

cache:
  directories:
    - $COMPOSER_CACHE_DIR

before_script:
  - composer selfupdate
  - composer require --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - vendor/bin/coveralls -v
